WIP: fix errors related to using sparse matrices/vectors [miqcp_proj]
1. vtype can't be a sparse vector. Error message is:
```
Error in .V.kind(from) :
  not yet implemented for matrix with typeof character
```

2. Can't combine a sparse vector with NULL, i.e., c(sparsevec, NULL).
   Error message is:
```
Error: node stack overflow
```
Hence, I needed to split up the definition of proj$rhs to two cases:
with preprocessing and without.